require("suryansh.plugins.comment")
require("suryansh.plugins-setup")
require("suryansh.core.options")
require("suryansh.core.keymaps")
require("suryansh.core.colorscheme")
require("suryansh.plugins.nvim-tree")
require("suryansh.plugins.lualine")
require("suryansh.plugins.autopairs")
require("suryansh.plugins.gitsigns")
require("suryansh.plugins.treesitter")
require("suryansh.plugins.telescope")
require("suryansh.plugins.nvim-cmp")
require("suryansh.plugins.lsp.mason")
require("suryansh.plugins.terraform")
require("suryansh.plugins.lsp.lspsaga")
require("suryansh.plugins.lsp.lspconfig")
require("suryansh.plugins.lsp.null-ls")
require("suryansh.plugins.gitblame")
require("suryansh.plugins.barbar")
require("suryansh.plugins.indent-line")
-- require("suryansh.plugins.min-indent")
-- require("suryansh.plugins.mini-animate")
require("suryansh.plugins.dashboard")
require("suryansh.plugins.fold")
require("suryansh.plugins.noice")
require("suryansh.plugins.colorizer")

vim.opt.foldmethod = "indent"
